// UI-chrome translation dictionary (static strings only — dynamic content
// from the database is translated via the *En/*Es/*Fr columns and the
// localizedField() helper in i18n.js, not here).
export const DICT = {
  nav: {
    pt: { home: "Início", noticias: "Notícias", campeonatos: "Campeonatos", pilotos: "Pilotos", resultados: "Resultados", calendario: "Calendário", virtual: "Drift Virtual", loja: "Loja", gridworks: "Grid Works" },
    en: { home: "Home", noticias: "News", campeonatos: "Championships", pilotos: "Drivers", resultados: "Results", calendario: "Calendar", virtual: "Sim Racing", loja: "Shop", gridworks: "Grid Works" },
    es: { home: "Inicio", noticias: "Noticias", campeonatos: "Campeonatos", pilotos: "Pilotos", resultados: "Resultados", calendario: "Calendario", virtual: "Sim Racing", loja: "Tienda", gridworks: "Grid Works" },
    fr: { home: "Accueil", noticias: "Actualités", campeonatos: "Championnats", pilotos: "Pilotes", resultados: "Résultats", calendario: "Calendrier", virtual: "Sim Racing", loja: "Boutique", gridworks: "Grid Works" },
  },

  common: {
    pt: {
      readMore: "Ler mais", viewAll: "Ver todos", viewAllNews: "Todas as notícias", viewAllDrivers: "Ver todos os pilotos",
      cart: "Carrinho", instagram: "@_driftfactory", followUs: "Segue-nos", search: "Pesquisar",
      home: "Início", loading: "A carregar…", seeResults: "Ver resultados", seeCalendar: "Ver calendário",
    },
    en: {
      readMore: "Read more", viewAll: "View all", viewAllNews: "All news", viewAllDrivers: "View all drivers",
      cart: "Cart", instagram: "@_driftfactory", followUs: "Follow us", search: "Search",
      home: "Home", loading: "Loading…", seeResults: "See results", seeCalendar: "See calendar",
    },
    es: {
      readMore: "Leer más", viewAll: "Ver todos", viewAllNews: "Todas las noticias", viewAllDrivers: "Ver todos los pilotos",
      cart: "Carrito", instagram: "@_driftfactory", followUs: "Síguenos", search: "Buscar",
      home: "Inicio", loading: "Cargando…", seeResults: "Ver resultados", seeCalendar: "Ver calendario",
    },
    fr: {
      readMore: "Lire plus", viewAll: "Voir tout", viewAllNews: "Toutes les actualités", viewAllDrivers: "Voir tous les pilotes",
      cart: "Panier", instagram: "@_driftfactory", followUs: "Suivez-nous", search: "Rechercher",
      home: "Accueil", loading: "Chargement…", seeResults: "Voir les résultats", seeCalendar: "Voir le calendrier",
    },
  },

  home: {
    pt: {
      eyebrow: "Portugal · Europa · Drift",
      h1a: "A fábrica", h1b: "do", h1c: "drift", h1d: "português.",
      lede: "Notícias, campeonatos, pilotos e resultados — tudo o que precisas para acompanhar a cena do drift em Portugal e no resto da Europa, num só sítio.",
      ctaNews: "Ver notícias", ctaChamps: "Campeonatos",
      statChamps: "Campeonatos seguidos", statDrivers: "Pilotos catalogados", statEvents: "Eventos por época",
      seasonTag: "Época 2026",
      newsEyebrow: "Últimas", newsTitle: "Notícias em destaque",
      champsEyebrow: "Séries", champsTitle: "Campeonatos que seguimos",
      virtualEyebrow: "Sim racing", virtualTitle: "Drift Virtual: a liga que nunca fecha o autódromo",
      virtualLede: "Junta-te à comunidade que compete em Assetto Corsa, sobe no leaderboard semanal e junta-te aos eventos ao vivo com a comunidade Drift Factory.",
      virtualCta: "Entrar na liga",
      partnersEyebrow: "Parceiros", partnersTitle: "Quem torna isto possível",
      driversEyebrow: "Grelha", driversTitle: "Pilotos em destaque",
      nextEventEyebrow: "Próximo evento",
      newsletterEyebrow: "Newsletter", newsletterTitle: "Fica na zona.",
      newsletterLede: "Sê o primeiro a saber o que se passa no mundo do drift — direto na tua caixa de correio.",
      noNews: "Ainda não há notícias publicadas.", noChamps: "Ainda não há campeonatos registados.", noDrivers: "Ainda não há pilotos registados.",
      welcome: "Bem-vindo à Drift Factory", readNews: "Ler notícia", nextEventTag: "Próximo evento",
    },
    en: {
      eyebrow: "Portugal · Europe · Drift",
      h1a: "The", h1b: "home of", h1c: "drift", h1d: "in Portugal.",
      lede: "News, championships, drivers and results — everything you need to follow the drift scene in Portugal and the rest of Europe, in one place.",
      ctaNews: "See news", ctaChamps: "Championships",
      statChamps: "Championships followed", statDrivers: "Drivers catalogued", statEvents: "Events per season",
      seasonTag: "2026 Season",
      newsEyebrow: "Latest", newsTitle: "Featured news",
      champsEyebrow: "Series", champsTitle: "Championships we follow",
      virtualEyebrow: "Sim racing", virtualTitle: "Drift Virtual: the league that never closes the track",
      virtualLede: "Join the community racing in Assetto Corsa, climb the weekly leaderboard and join live events with the Drift Factory community.",
      virtualCta: "Join the league",
      partnersEyebrow: "Partners", partnersTitle: "Who makes this possible",
      driversEyebrow: "Grid", driversTitle: "Featured drivers",
      nextEventEyebrow: "Next event",
      newsletterEyebrow: "Newsletter", newsletterTitle: "Stay in the loop.",
      newsletterLede: "Be the first to know what's happening in the drift world — straight to your inbox.",
      noNews: "No news published yet.", noChamps: "No championships registered yet.", noDrivers: "No drivers registered yet.",
      welcome: "Welcome to Drift Factory", readNews: "Read article", nextEventTag: "Next event",
    },
    es: {
      eyebrow: "Portugal · Europa · Drift",
      h1a: "La fábrica", h1b: "del", h1c: "drift", h1d: "portugués.",
      lede: "Noticias, campeonatos, pilotos y resultados — todo lo que necesitas para seguir la escena del drift en Portugal y el resto de Europa, en un solo sitio.",
      ctaNews: "Ver noticias", ctaChamps: "Campeonatos",
      statChamps: "Campeonatos seguidos", statDrivers: "Pilotos catalogados", statEvents: "Eventos por temporada",
      seasonTag: "Temporada 2026",
      newsEyebrow: "Últimas", newsTitle: "Noticias destacadas",
      champsEyebrow: "Series", champsTitle: "Campeonatos que seguimos",
      virtualEyebrow: "Sim racing", virtualTitle: "Drift Virtual: la liga que nunca cierra el circuito",
      virtualLede: "Únete a la comunidad que compite en Assetto Corsa, sube en el leaderboard semanal y participa en eventos en directo con la comunidad Drift Factory.",
      virtualCta: "Entrar en la liga",
      partnersEyebrow: "Socios", partnersTitle: "Quién hace esto posible",
      driversEyebrow: "Parrilla", driversTitle: "Pilotos destacados",
      nextEventEyebrow: "Próximo evento",
      newsletterEyebrow: "Newsletter", newsletterTitle: "Mantente al día.",
      newsletterLede: "Sé el primero en saber qué pasa en el mundo del drift — directo a tu correo.",
      noNews: "Aún no hay noticias publicadas.", noChamps: "Aún no hay campeonatos registrados.", noDrivers: "Aún no hay pilotos registrados.",
      welcome: "Bienvenido a Drift Factory", readNews: "Leer noticia", nextEventTag: "Próximo evento",
    },
    fr: {
      eyebrow: "Portugal · Europe · Drift",
      h1a: "L'usine", h1b: "du", h1c: "drift", h1d: "portugais.",
      lede: "Actualités, championnats, pilotes et résultats — tout ce qu'il faut pour suivre la scène du drift au Portugal et dans le reste de l'Europe, au même endroit.",
      ctaNews: "Voir les actualités", ctaChamps: "Championnats",
      statChamps: "Championnats suivis", statDrivers: "Pilotes répertoriés", statEvents: "Événements par saison",
      seasonTag: "Saison 2026",
      newsEyebrow: "Dernières", newsTitle: "Actualités à la une",
      champsEyebrow: "Séries", champsTitle: "Championnats que nous suivons",
      virtualEyebrow: "Sim racing", virtualTitle: "Drift Virtual : la ligue qui ne ferme jamais le circuit",
      virtualLede: "Rejoins la communauté qui course sur Assetto Corsa, grimpe au classement hebdomadaire et participe aux événements en direct avec la communauté Drift Factory.",
      virtualCta: "Rejoindre la ligue",
      partnersEyebrow: "Partenaires", partnersTitle: "Qui rend tout ça possible",
      driversEyebrow: "Grille", driversTitle: "Pilotes à la une",
      nextEventEyebrow: "Prochain événement",
      newsletterEyebrow: "Newsletter", newsletterTitle: "Reste connecté.",
      newsletterLede: "Sois le premier informé de l'actualité du monde du drift — directement dans ta boîte mail.",
      noNews: "Aucune actualité publiée pour le moment.", noChamps: "Aucun championnat enregistré pour le moment.", noDrivers: "Aucun pilote enregistré pour le moment.",
      welcome: "Bienvenue à Drift Factory", readNews: "Lire l'article", nextEventTag: "Prochain événement",
    },
  },

  footer: {
    pt: {
      tagline: "Tudo sobre o drift em Portugal e no resto da Europa — notícias, campeonatos, pilotos, resultados e muito mais.",
      explore: "Explorar", more: "Mais", legal: "Legal", newsletter: "Newsletter",
      newsletterLede: "Recebe as novidades do drift direto na tua caixa de correio.",
      regulation: "Regulamento",
      rights: "Todos os direitos reservados.",
      demo: "Conteúdo de demonstração — site em construção.",
      complaintsBook: "Livro de Reclamações Eletrónico",
      terms: "Termos e Condições", privacy: "Política de Privacidade", returns: "Trocas e Devoluções",
      complaints: "Livro de Reclamações", disputes: "Resolução de Litígios",
    },
    en: {
      tagline: "Everything about drift in Portugal and the rest of Europe — news, championships, drivers, results and much more.",
      explore: "Explore", more: "More", legal: "Legal", newsletter: "Newsletter",
      newsletterLede: "Get drift news straight to your inbox.",
      regulation: "Rules",
      rights: "All rights reserved.",
      demo: "Demo content — site under construction.",
      complaintsBook: "Electronic Complaints Book",
      terms: "Terms & Conditions", privacy: "Privacy Policy", returns: "Returns & Exchanges",
      complaints: "Complaints Book", disputes: "Dispute Resolution",
    },
    es: {
      tagline: "Todo sobre el drift en Portugal y el resto de Europa — noticias, campeonatos, pilotos, resultados y mucho más.",
      explore: "Explorar", more: "Más", legal: "Legal", newsletter: "Newsletter",
      newsletterLede: "Recibe las novedades del drift directo en tu correo.",
      regulation: "Reglamento",
      rights: "Todos los derechos reservados.",
      demo: "Contenido de demostración — sitio en construcción.",
      complaintsBook: "Libro de Reclamaciones Electrónico",
      terms: "Términos y Condiciones", privacy: "Política de Privacidad", returns: "Cambios y Devoluciones",
      complaints: "Libro de Reclamaciones", disputes: "Resolución de Litigios",
    },
    fr: {
      tagline: "Tout sur le drift au Portugal et dans le reste de l'Europe — actualités, championnats, pilotes, résultats et bien plus.",
      explore: "Explorer", more: "Plus", legal: "Légal", newsletter: "Newsletter",
      newsletterLede: "Reçois les actualités du drift directement dans ta boîte mail.",
      regulation: "Règlement",
      rights: "Tous droits réservés.",
      demo: "Contenu de démonstration — site en construction.",
      complaintsBook: "Livre de Réclamations Électronique",
      terms: "Conditions Générales", privacy: "Politique de Confidentialité", returns: "Échanges et Retours",
      complaints: "Livre de Réclamations", disputes: "Résolution des Litiges",
    },
  },
};

export function t(namespace, locale) {
  return DICT[namespace]?.[locale] || DICT[namespace]?.pt || {};
}
